spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/ai_code_gen
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600