spring:
  application:
    name: AICodeGen-Backend
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /api

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEKSEEK_API_KEY}
      model-name: deepseek-chat
      max-tokens: 2048
      log-requests: true
      log-responses: true
      max-retries: 3
      timeout: 300s
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEKSEEK_API_KEY}
      model-name: deepseek-chat
      max-tokens: 2048
      log-requests: true
      log-responses: true
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEKSEEK_API_KEY}
      model-name: deepseek-reasoner
      max-tokens: 8192
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DEEKSEEK_API_KEY}
      model-name: qwen-turbo
      max-tokens: 100
      log-requests: true
      log-responses: true
      
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: xyz.kbws.aicodegenbackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
